### PR TITLE
Allow slash in name

### PR DESCRIPTION
**Pull request by XLordalX**
This adds GitLab nested group support to pipelines.

### CODE REVIEW

**Comment by ankitm123** [comment]
Tests would be good to ensure we don't add regression. I added some changes to support nested gitlab repos, I must have missed certain parts. Thanks for looking into this and fixing it :)

**Comment by ankitm123** [comment]
Does it fix issues around jx pipeline start? Curious ...

**Comment by XLordalX** [comment]
Yes it does, it gets stuck on the pipeline wait command because it's waiting for the wrong trigger:

```
waiting up to 20m0s for a trigger to be added to the lighthouse configuration in ConfigMap config in namespace jx for repository: org/subgroup-subproject
you can watch the boot job to update the configuration via: jx admin log
for more information on how this works see: https://jenkins-x.io/v3/about/how-it-works/#importing--creating-quickstarts
```

but instead it's supposed to wait for `org/subgroup/subproject` (notice the dash was replaced with a slash). This change fixes that.

**Comment by ankitm123** [comment]
Did u try --nested-repo flag when importing?

**Comment by XLordalX** [comment]
> Did u try --nested-repo flag when importing?

Yes. This is with —nested-repo.

**Comment by XLordalX** [comment]
@ankitm123 I'm willing to write tests for this, but I'm not sure what needs to be tested. Can you help me out a bit?

**Comment by msvticket** [comment]
I think this is the wrong fix for the problem. The method is meant for creating k8s resource names and they can not have /. Instead some other method (possibly new) should be used.

**Review by msvticket — CHANGES_REQUESTED** [review]
I think this is the wrong fix for the problem. The method is meant for creating k8s resource names and they can not have /. Instead some other method (possibly new) should be used.

**Pull request closed without merging**
